export { default as blue } from './blue';
export { default as lightBlue } from './light-blue';
export { default as cyan } from './cyan';
export { default as indigo } from './indigo';
export { default as pink } from './pink';
export { default as purple } from './purple';
export { default as deepPurple } from './deep-purple';
export { default as red } from './red';
export { default as teal } from './teal';
